In [17]:
import numpy as np

In [18]:
#Array 1D

d1 = np.array([1,2,3])
print(d1)

[1 2 3]


In [19]:
d1.shape    # index

(3,)

In [20]:
d1.ndim     #Dimeções

1

In [21]:
d1.dtype    #tipo da aray

dtype('int32')

In [22]:
#Array 2D

d2 = np.array([[1,2,3],[4,5,6]])
print(d2)

[[1 2 3]
 [4 5 6]]


In [23]:
d2.shape    # index

(2, 3)

In [24]:
d2.ndim     #Dimeções

2

In [25]:
d2.dtype    #tipo da aray

dtype('int32')

In [38]:
#Array 3D

d3 = np.array([[[1,2] , [3,4]] ,[[5,6],[7,8]]])
print(d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
d3.shape    # index

(2, 2, 2)

In [40]:
d3.ndim     #Dimeções

3

In [41]:
d3.dtype    #tipo da aray

dtype('int32')